@startuml Activity Diagram - Customize Greeting Message

skinparam dpi 150
skinparam activityPadding 6
skinparam activityMargin 6
skinparam arrowThickness 1
skinparam notePadding 4
skinparam shadowing false
skinparam defaultFontSize 11
|User|
start
|System|

:(1) Display greeting settings view;

|User|
:(2) Edit greeting message;
:(3) Click "Save";

|System|
:(4) Validate message;
if (Valid?) then (Invalid)
  :(4.1) Display error;
else (Valid)
  |Database|
  :(5) Store greeting message;
  if (Store failed?) then (Error)
    |System|
    :(5.1) Display error;
  else (Success)
    |System|
    :(6) Display success;
    stop
  endif
endif

@enduml